from .usuario import UsuarioSchema
from .foto import FotoSchema
from .livro import LivroSchema
from .referencia import ReferenciaSchema
from .videos import VideosSchema
from .livro_vida import LivroVidaSchema
from .fichas_atividades import FichasAtividadesSchema
from .fichas_conteudos import FichasConteudosSchema
from .cartografias import CartografiasSchema
